FROM golang:1.24.2-alpine3.21 as builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go build -o /app/queue ./cmd/queue/main.go

FROM alpine:3.21
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/queue /app/queue
CMD ["/app/queue"]